wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695826937.600094
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 79
      3:
      - 13
      - 15
      - 23
      4: 3.9.17
      5: 0.15.5
      6: 4.31.0
      8:
      - 5
